# Service config
server.port=8083
spring.application.name=smart-assistant
server.servlet.context-path=/assistant-service

# Chat model
# Chat model
#spring.ai.model.chat=openAi
# API Key

#
# ==============================================
# Default chat model settings ? applied globally
# ==============================================
#spring.ai.ollama.chat.options.model=llama3.2:1b
# Optional ? commonly used tuning parameters
#spring.ai.ollama.chat.options.temperature=0.75
#spring.ai.ollama.chat.options.num-predict=800
#spring.ai.ollama.chat.options.top-p=0.9
#spring.ai.ollama.chat.options.top-k=40
#spring.ai.ollama.chat.options.repeat-penalty=1.1
#spring.ai.ollama.chat.options.max-tokens=10
#spring.ai.ollama.init.pull-embedding-model=false

#spring.ai.ollama.init.pull-model-strategy=when-missing
#spring.ai.ollama.init.timeout=120s

#Logging
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

logging.level.root=INFO
logging.level.com.inchbyinch=DEBUG
logging.level.org.springframework.ai=DEBUG
spring.devtools.add-properties = false

## DB
spring.datasource.url=jdbc:h2:file:./smartassistant
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=kishan
spring.datasource.password=help@123

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:schema/schema-h2db.sql

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=smartassist

##
tavily.api.key=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
tavily.default.result.limit=5
tavily.base.url=https://api.tavily.com/

